public enum ProgressEvent
{
    None,
    GameStart,
    MoveInMonologue,
    SearchMat,
    KeyNotFoundMonologue,
    FindKeyInTrash,
    KeyFoundMonologue,
    MoveInBoxes,
    DoorKnock,
    GoToNeighborsHouse,
    NeighborWelcome,
    ExploreNeighborsHouse,
    TeaReadyDialogue,
    TeaReady,
    StayTheNightDialogue,
    StayTheNightDecision,
    // Events that only happen if investigating blood/clues.
    GoToSleep,
    SeeBlood,
    FindToolToOpenDoor,
    OpenBloodiedDoor,
    SeeBody,
    MoveCameraToBody,
    CorpseJumpscare,
    MoveCameraToNeighborAndBody,
}